- hosts: localhost
  connection: local   # <-- SSH ki zarurat nahi, directly local system
  become: yes
  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Build Java Docker image
      command: docker build -t java-ansible-app .
      args:
        chdir: /home/ec2-user/Ansible-Automation-On-AWS/AnsibleJavaDeployer/AnsibleJavaApp

    - name: Stop old container if exists
      command: docker rm -f java-ansible-container
      ignore_errors: yes

    - name: Run container
      command: docker run -d --name java-ansible-container -p 8080:8080 java-ansible-app
